### ISSUE TITLE
Visible background color looks more dark than backgroundColor property

### ISSUE THREAD

**Issue by muratmusic** [bannzai/SpreadsheetView#129] opened 2017-08-16 07:34 UTC
## Expected Behavior
Visible background color should be equal to backgroundColor properties of SpreadsheetView and its cells and contentView's of cells

## Actual Behavior
Visible background color looks more dark than backgroundColor properties

## Steps to Reproduce the Problem

  1. Make test app with SpreadsheetView.
  2. Set backgroundColor properties of SpreadsheetView and its cells and contentView's of cells to RGB 0x1E1E1E.
  3. Run the app
  4. Make a screenshot of SpreadsheetView
  5. Open screenshot with any Graphical Editor app to pick color of SpreadsheetView. Its color is more dark than RGB 0x1E1E1E.

## Specifications

  - Xcode version: 9 beta 5
  - iOS version: 11
  - Dependency manager + version: No dependency manager

**Comment by kishikawakatsumi** [comment] 2017-08-16 11:07
@muratmusic I cannot reproduce the issue. It cannot be assumed that such an issue will happen. Probably `alpha` value is different? Could you please provide repro case and a screenshot?

**Comment by kishikawakatsumi** [comment] 2017-08-21 11:57
It looks to me as if we've answered your question. I'm going to close this issue. Please feel absolutely free to open a new one if you have more questions.

**Closed as completed by kishikawakatsumi** 2017-08-21 11:57 UTC
Labels: reproduction needed

**Comment by muratmusic** [comment] 2017-08-21 12:42
I'm sorry for delay. Ok, thanks.
