### ISSUE TITLE
Cell widths and heights that aren't whole numbers cause graphical glitches on the cell borders.

### ISSUE THREAD

**Issue by babramovitch** [bannzai/SpreadsheetView#91] opened 2017-07-01 22:00 UTC
Hi,

First off I just want to say, what a wonderful library.  I didn't think I'd be able to get a grid schedule into my app for the upcoming festival this year due to time, but it's been so easy to work with, I had the schedule fully loaded in under a day and started adding my own functionality ontop of it with ease.  Well done.  Super flexible.

I'm working on a schedule view, where I have a day/night theme.  On the day theme, things worked properly, but when I went into night theme, I started getting weird color artifacts on the borders.

There's two columns that have a persistent border visible, even though my borders are the same color as the cell backgrounds with no content.  All cells get the same border applied. 

I also had similar problems with a zoom functionality I implemented which adjusts the cell height.  I'd get graphical glitches as I zoomed in/out showing white borders on my black background briefly, and when my zooming was done, some would sometimes remain.

I tracked it down to my dynamically generated height/widths of the cells being non whole numbers.

As soon as I took the final result of my column width, or how zoomed things were and rounded the answers down, the problems went away.

My assumption is the glitches aren't noticeable on a white background since they're white. 

Here's an image of what it looks like, post zooming.   Not sure if this is something fixable in the library short of rounding peoples values yourself, but should anyone encounter this, that's what's up.

![screen shot 2017-08-13 at 2 30 54 pm](https://user-images.githubusercontent.com/3608443/27765677-1de0d5ea-5e6d-11e7-97c5-502106816d50.png)

**Comment by kishikawakatsumi** [comment] 2017-07-22 04:32
I'm not sure it would be better fixing this issue on the library side, but I will try it. Can you provide a reproducible sample project? @babramovitch

**Comment by babramovitch** [comment] 2017-07-22 04:52
@kishikawakatsumi I agree, it might not be best library side.  Mainly, I wanted to post this here so others would be aware of it should they encounter it and wonder what was going on.

When I get a chance, I'll try putting together a sample app.

**Comment by babramovitch** [comment] 2017-07-23 20:28
@kishikawakatsumi  So I downloaded the sample project with the library and tried changing the numbers for the width/height in the schedule section and added a black cell background and it creates the problem on my iPhone 6

Original File: https://github.com/kishikawakatsumi/SpreadsheetView/blob/master/Examples/Schedule/Sources/ViewController.swift

Gist with below changes: https://gist.github.com/babramovitch/30140cbac538361ee2160d4b58b3f4f9

```
 func spreadsheetView(_ spreadsheetView: SpreadsheetView, widthForColumn column: Int) -> CGFloat {
        if case 0 = column {
            return 70
        } else {
            return 120.3910948
        }
    }

```
    func spreadsheetView(_ spreadsheetView: SpreadsheetView, heightForRow row: Int) -> CGFloat {
        if case 0 = row {
            return 24
        } else if case 1 = row {
            return 32
        } else {
            return 40.390852
        }
    }

I also added a black cell background at the bottom of the if/else chain

          if !text.isEmpty {
                cell.label.text = text
                let color = dayColors[indexPath.column - 1]
                cell.label.textColor = color
                cell.color = color.withAlphaComponent(0.2)
                cell.borders.top = .solid(width: 2, color: color)
                cell.borders.bottom = .solid(width: 2, color: color)

            } else {
                cell.label.text = nil
                cell.color = indexPath.row % 2 == 0 ? evenRowColor : oddRowColor
                cell.borders.top = .none
                cell.borders.bottom = .none
            }
            cell.backgroundColor = UIColor.black

First image is with the changes, second image is with the whole number values 120/40.

First image is in landscape just as it's more visible, 2nd in portrait just to show it's normal

![img_0010](https://user-images.githubusercontent.com/3608443/28502594-b19ce0c8-6faa-11e7-89e2-45e96316759a.PNG)
![img_0008](https://user-images.githubusercontent.com/3608443/28502595-b3c53ec2-6faa-11e7-8019-0b58f8aa41d5.PNG)

**Comment by kishikawakatsumi** [comment] 2017-08-14 18:41
@babramovitch Sorry for the late reply. I'm going to close this issue because it doesn't make sense to specify the values like `120.3910948` or `40.390852`. Passing correct value is programmer's responsibility, not library side.

Please let me know and reopen if I understand wrong.

**Closed as completed by kishikawakatsumi** 2017-08-14 18:41 UTC

**Comment by babramovitch** [comment] 2017-08-14 20:14
@kishikawakatsumi I don't think this should be closed for that reason.   My problem happened because I was dynamically calculating the width of the cells so X cells would fit on the screen at a time at the largest size possible. 

If anyone else does this,  they'll encounter the same problem unless they take the rounded value of their calculations

**Comment by kishikawakatsumi** [comment] 2017-08-15 07:59
@babramovitch So you meant that it should be rounded the numbers on the library side, right?

**Comment by babramovitch** [comment] 2017-08-15 17:37
@kishikawakatsumi not sure if rounding  someone's numbers to a whole number would be best,  I haven't fully played around with the problem, maybe it works with 1 or 2 decimals but no more?  In my case the division to determine the number made it many decimals.  Maybe 4.5 works fine though. 

If even 1 decimal causes the problem though ,  making it accept an integer might be the better option? 

It also only happens if the background is a different color so maybe just a note in the read me works as well?

**Comment by kishikawakatsumi** [comment] 2017-08-16 14:07
@babramovitch As using UIKit components, such behavior is expected. Since most devices have a Retina display, the `.5` point is equal to 1 pixel, so it is aligned to pixels (except iPhone 6 Plus and iPhone 6s Plus).  Because it is quite obvious that it blurs when specifying any other floating point, I don't think that it is worth to mention it in the README. Also, in this case, a programmer should have the responsibility to adjust the parameters correctly, it is not a good behavior that library to arbitrarily round it.

See also https://developer.apple.com/library/content/documentation/2DDrawing/Conceptual/DrawingPrintingiOS/GraphicsDrawingOverview/GraphicsDrawingOverview.html#//apple_ref/doc/uid/TP40010156-CH14-SW7

Does it answer for you?

**Comment by babramovitch** [comment] 2017-08-18 18:46
@kishikawakatsumi  I think that explains why it's doing it well.  I do agree that arbitrarily rounding someones numbers probably isn't the best solution.  If not a mention in the readme, what do you think about outputting a warning with NSLog if the number isn't a whole number or .5?  Although, if that's not done in a good way it would be super spammy.

I may be wrong, but I don't think it's unreasonable for people to think "I want 4.2 columns to show at once on all different screen sizes, so they see 4 full columns, and the start of the 5th so they know it's there" and go `width = screenWidth / 4.2`.  You never see the actual number in a scenario like this when looking in the code for what could be causing issues, and it's expecting a CGFloat return value.

Some mention somewhere, could save people some hours of frustration until they find this thread otherwise.

For example, this is my actual code which I ended up adding the round to solve the problem

```
func spreadsheetView(_ spreadsheetView: SpreadsheetView, widthForColumn column: Int) -> CGFloat {

        if case 0 = column {
            return 70
        } else {
            var width: CGFloat

            if currentOrientation == Orientation.PORTRAIT {
                width = (self.view.frame.width / 5.2) 
            } else {
                width = (self.view.frame.width / 8) 
            }

            return width.rounded(.down)
        }
    }
```
