### ISSUE TITLE
xCode 9 Beta - Swift 3.2/4 Compatibility With Schedule Example

### ISSUE THREAD

**Issue by bawelter** [bannzai/SpreadsheetView#88] opened 2017-06-30 15:13 UTC
Tested the Schedule Example out on xCode 9 with the Swift 4 compiler as Swift version 3.2 in the build settings and it would compile but when trying to open in the emulator it would crash.  All other examples worked fine.

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SpreadsheetView.SpreadsheetView refreshControl]: unrecognized selector sent to instance 0x7fdc6f72c2a0'

![error](https://user-images.githubusercontent.com/3850531/27742007-ada9d9e8-5d7c-11e7-886e-029d07d688cd.jpeg)

**Comment by bawelter** [comment] 2017-06-30 15:32
Looks like this is a problem whenever a Navigation Controller has the SpreadsheetView as a Root View Controller.  I will be looking into the issue to see if I can find a solution.

**Comment by bawelter** [comment] 2017-06-30 17:45
Looks like this issue is the same as issue #83

**Comment by kishikawakatsumi** [comment] 2017-07-01 05:46
@bawelter 
Yes. Closing duplicate of https://github.com/kishikawakatsumi/SpreadsheetView/issues/83

**Closed as completed by kishikawakatsumi** 2017-07-01 05:46 UTC
