### ISSUE TITLE
How to adjust table to full screen

### ISSUE THREAD

**Issue by Vidhanshu09** [bannzai/SpreadsheetView#183] opened 2018-03-13 09:00 UTC
## Expected Behavior
I need that if i have only two headers then table should automatically adjust its width and fits to full screen.

## Actual Behavior
but the table width is fix 

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Xcode version: Xcode 9.2
  - iOS version: ios 11
  - Dependency manager + version: ?

**Comment by Vidhanshu09** [comment] 2018-03-13 09:01
Swift 4

**Comment by kishikawakatsumi** [comment] 2018-03-13 09:04
I cannot understand what you meant. Please explain more specific, like using a screenshot, example code or diagram. @Vidhanshu09

**Comment by Vidhanshu09** [comment] 2018-03-13 09:09
![simulator screen shot - ipad air - 2018-03-13 at 14 37 18](https://user-images.githubusercontent.com/37325439/37332267-2eb0bf70-26cc-11e8-83e0-c116d355a87a.png)
I want this attached screen like below attached screen which fits to whole screen
![simulator screen shot - ipad air - 2018-03-13 at 14 37 31](https://user-images.githubusercontent.com/37325439/37332318-59389c90-26cc-11e8-9401-53edca55c687.png)

**Comment by kishikawakatsumi** [comment] 2018-03-13 09:17
@Vidhanshu09 You seem to be misconfiguring the size of the view. I recommend you learn about Autolayout.

**Comment by Vidhanshu09** [comment] 2018-03-13 09:22
i don't need any recommendation from you, i know what Autolayout is. i don't think you have any idea that how to adjust it in whole screen so i am closing it.

**Comment by AnthoPakPak** [comment] 2018-03-21 09:04
I am also interested in this feature, which has nothing to do with AutoLayout. On the first screenshot of @Vidhanshu09, the white space on the right is not filled by cells but it's still the spreadsheet ! On the second screen, he tried to guess the best size of his cells in order to fill the white space. But it's hard to guess the correct size for every screen, specially if the columns have different sizes. 

Does anybody has a clue to achieve this behavior ? I don't think it should be closed, as it is a feature a lot of people should be interested.

**Comment by trond-eskeland** [comment] 2018-03-21 13:08
It would be nice to have a built in support for this. If anyone is interested here is the code I’m using in one of my project. Calculating the column sizes to match max row text width size and fit screen size if it is too small.

```
calcColumSizes(UIScreen.main.bounds.width)

func calcColumSizes(_ width:CGFloat) {
	if self.dataFilter.count > 0 && self.header.count > 0 {
		var data = self.dataFilter
		data.append(header)
		
		let font = UIFont.systemFont(ofSize: 14)
		
		let count = header.count
		self.columSize = []
		for i in 0...count - 1  {
			
			if let max = data.max(by:  { $1.count == count && $0.count == count &&   $1[i].count > $0[i].count}) {
				self.columSize.append(max[i].width(withConstrainedHeight: 25, font: font))
				
			}
		}
		fixColumScreenSize(width)
	}
  
}

func fixColumScreenSize(_ screenWidth:CGFloat) {
	var total:CGFloat = 0
	for item in self.columSize {
		total += item
	}
	let toAdd = (screenWidth - total) /  CGFloat(self.columSize.count)
	if toAdd > 0 {
		var newColumSize:[CGFloat] = []
		for item in self.columSize {
			newColumSize.append(item + toAdd)
		}
		self.columSize = newColumSize
	}
}

```

**Comment by kishikawakatsumi** [comment] 2018-03-21 16:33
@AnthoPakPak Can you please share how to reproduce the problem. It looks like a just misconfiguration to me, but is not it?

**Comment by kishikawakatsumi** [comment] 2018-03-25 09:18
Closing due to lack of information. Feel free to reopen if you have further information

**Closed as completed by kishikawakatsumi** 2018-03-25 09:18 UTC
Labels: reproduction needed

**Comment by AnthoPakPak** [comment] 2018-03-26 07:37
@kishikawakatsumi I don't understand why you say it's a misconfiguration. As there is a delegate to define columns width, it appears evident that the table will not fit to the screen width. If there was any AutomaticWidth, it will be possible, but I don't think it's the case for the moment. 
If I return 10 in column width delegate, and having 4 columns, you're agree that it will not take all width space, even with autolayout, isn't it ?
