### ISSUE TITLE
`reloadData()` doesn't reflect the latest data source

### ISSUE THREAD

**Issue by rogpfreck** [bannzai/SpreadsheetView#21] opened 2017-05-15 20:29 UTC
Hi Kishikawa,

Thanks for a really excellent spreadsheet view, which I have incorporated into my app.

One problem. I change some settings and try to refresh the spreadsheetView with the usual:

spreadsheetView.reloadData()  or
spreadsheetView.setNeedsDisplay()

But this has no effect on  

func spreadsheetView(_ spreadsheetView: SpreadsheetView, cellForItemAt indexPath: IndexPath) -> Cell?

Any suggestions?

Thanks

Roger

**Comment by kishikawakatsumi** [comment] 2017-05-16 00:32
@rogpfreck Because of the `spreadsheetView (_: cellForItemAt:)` method is called during the layout process, the `needsReload` flag is cleared at the end of the layout process.
Calling `reloadData ()` inside `spreadsheetView (_: cellForItemAt:)` doesn't make sense, for example, doing the same thing with `UITableView` will also produce unexpected behavior. Could you please elaborate why you want to do so and what you would like to achieve, also show your code?

**Comment by rogpfreck** [comment] 2017-05-16 14:20
Hi Kishikawa,

Thanks for your reply.

I have/had no intention of calling reloadData inside the func spreadsheetView (_: cellForItemAt:) . As you rightly point out that would be daft.

Rather I wanted to call reloadData() outside of the func so that it would refresh the data that is being used by spreadsheetView. If spreadsheetView was a standard tableView this would be a trivial matter as reloadData() is used, as you know, precisely for that purpose.

My point is that treating spreadsheetView as though is was a tableView and trying to refresh it outside of the func does not work. Or at least as far as I can ascertain. Here's a trivial example.

1. The spreadsheetView is displayed with data.
2. User wants to change something so they go to a popover settings view and for example, select a different colour of text to be used in a cell.
3. ReloadData() is called when the user is finished.
4. In the spreadsheetView (_: cellForItemAt:) these changes can be manipulated easily, if it was invoked.

But spreadsheetView (_: cellForItemAt:) does not get called on reloadData()

I tried this with your fine Gantt example, by placing a button on a top toolbar on the view controller , and firing ReloadData() from there. No effect.

I trust this helps to clarify things.

Roger

**Comment by blainerothrock** [comment] 2017-05-16 15:28
I am also seeing this issue, I am trying to reload the data after touching a header cell to sort data:

```Swift
func spreadsheetView(_ spreadsheetView: SpreadsheetView, didSelectItemAt indexPath: IndexPath) {
        if let _ = spreadsheetView.cellForItem(at: indexPath) as? HeaderCell {
            self.data.sort { $0 < $1 }
            print(self.data)
            ssview.reloadData()
        }
    }
```

nothing happens initially, but when I scroll and the cells refresh and the data is sorted.

I also tried forcing on the main thread: 

```Swift
DispatchQueue.main.async {
  self.ssview.reloadData()
}
```

**Comment by jpopham** [comment] 2017-05-16 22:21
I'm having the same issue, for the same use case as blainerothrock.

**Comment by kishikawakatsumi** [comment] 2017-05-17 09:59
@rogpfreck @blainerothrock @jpopham I found a rendering issue after reloading. But reloading data seems to work correctly. Can anyone provide a reproducible sample project?

**Comment by blainerothrock** [comment] 2017-05-17 13:45
[here](https://github.com/kishikawakatsumi/SpreadsheetView/files/1007920/spreadsheet-poc.zip) you go. In this project, I am comparing SpreadsheetView and SwiftSpreadsheetView. The code for SpreadsheetView can be found in `ViewController.swift` and `Cells.swift`

In the SpreadsheetView, when clicking on the "Name" header cell, the first column should be sorted by alphabetical order. You can see this in the console log, but The view does not update until you scroll down the page and cells are redrawn when entering the view port.

Let me know if you have any questions.

**Comment by jpopham** [comment] 2017-05-17 16:09
[Another Example](https://github.com/kishikawakatsumi/SpreadsheetView/files/1008353/testSS.zip).  Clicking on the "Change Value" button updates a UILabel, a UITableView and a UICollectionView - the latter two by calling there reloadData() method.  The reloadData() method of SpreadsheetView is also called, but the SpreadsheetView display doesn't update.

**Comment by windy48** [comment] 2017-05-18 10:47
I'm also facing this issue.
I have found out that if the number of rows or columns wasn't changed It won't do the reload, hope this help.

**Comment by kishikawakatsumi** [comment] 2017-05-18 12:56
@blainerothrock @jpopham Thanks for the repro case. The cause of the issue is that reusing cell keeps old data after reloading 😥 It should be fixed by https://github.com/kishikawakatsumi/SpreadsheetView/pull/37, and I will release a new version soon.

**Comment by blainerothrock** [comment] 2017-05-18 13:59
Awesome, I tested on that branch and it is working! Thanks!

**Comment by jpopham** [comment] 2017-05-18 17:19
Yes that branch works for me too.  Thanks

**Closed as completed** 2017-05-19 05:13 UTC
Labels: bug, help wanted
