### ISSUE TITLE
UI misplaced when reloadData() with frozenColumns changed

### ISSUE THREAD

**Issue by Smiacter** [bannzai/SpreadsheetView#59] opened 2017-05-27 10:57 UTC
I have 4 buttons, and when I click one, I'll reloadData...
First I set frozenColumns to be 4, frozenRows to be 1, everything work fine, but when I click one button and reloadData(), set frozenColumns to be 0,  the UI misplaced. The later header and data resource are less than the former one.
![img_0166](https://cloud.githubusercontent.com/assets/5238096/26520875/e5e57166-430d-11e7-92cd-2a85f99e3452.png)

Why show this? expect your answer, thx.

**Comment by Smiacter** [comment] 2017-05-27 11:26
When set same frozenColumns, everything is OK!
`    func frozenColumns(in spreadsheetView: SpreadsheetView) -> Int {
//        return badType == .list ? 0 : 4   // UI misplaced
        return 4                            // UI OK
    }`

**Comment by Smiacter** [comment] 2017-05-27 11:27
When set same frozenColumns, everything is OK!
`func frozenColumns(in spreadsheetView: SpreadsheetView) -> Int { 
// return badType == .list ? 0 : 4 // UI misplaced
 return 4 // UI OK
 }`

**Comment by kishikawakatsumi** [comment] 2017-05-27 14:03
@Smiacter Could you provide a reproducible project? I cannot reproduce the issue yet.

**Comment by Smiacter** [comment] 2017-05-27 15:41
Thanks for you reply, here I wrote a demo that can reproducible the issue. 

In the demo, click button2 then click button1, the UI will misplace...

[UIMisPlaceIssue.zip](https://github.com/kishikawakatsumi/SpreadsheetView/files/1033636/UIMisPlaceIssue.zip)

**Comment by kishikawakatsumi** [comment] 2017-05-28 05:17
@Smiacter Thank you for the repro case. It should be fixed by https://github.com/kishikawakatsumi/SpreadsheetView/pull/60

**Closed as completed** 2017-05-28 09:40 UTC
Labels: help wanted
